# Generated by Django 4.1.1 on 2023-06-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_medication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dron',
            name='medicationLoad',
            field=models.ManyToManyField(to='Api.medication'),
        ),
    ]
