# Generated by Django 4.1.1 on 2023-06-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_dron_medicationload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dron',
            name='medicationLoad',
            field=models.ManyToManyField(blank=True, null=True, to='Api.medication'),
        ),
    ]
