# Generated by Django 4.1.1 on 2023-06-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_dron_medicationload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dron',
            old_name='weightLimit',
            new_name='weight',
        ),
    ]
