# Generated by Django 4.1.1 on 2023-06-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_rename_weightlimit_dron_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=100, verbose_name='Serial number')),
                ('model', models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], max_length=50, verbose_name='Model')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weigh limit')),
                ('battery', models.IntegerField(verbose_name='Battery')),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], max_length=50, verbose_name='State')),
                ('medicationLoad', models.ManyToManyField(blank=True, null=True, to='Api.medication')),
            ],
        ),
        migrations.DeleteModel(
            name='Dron',
        ),
    ]
