# Generated by Django 4.1.1 on 2023-06-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_drone_delete_dron'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='weight',
            new_name='weightLimit',
        ),
    ]
