# Generated by Django 4.1.1 on 2023-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_rename_weight_drone_weightlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.CharField(max_length=10000000, verbose_name='Image'),
        ),
    ]
