# Generated by Django 4.1.1 on 2023-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_medication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='medicationLoad',
            field=models.ManyToManyField(blank=True, to='Api.medication'),
        ),
    ]
