# Generated by Django 4.1.1 on 2023-06-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_alter_drone_medicationload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='state',
            field=models.CharField(choices=[('IDLE', 'IDLE'), ('LOADING', 'LOADING'), ('LOADED', 'LOADED'), ('DELIVERING', 'DELIVERING'), ('DELIVERED', 'DELIVERED'), ('RETURNING', 'RETURNING')], default='IDLE', max_length=50, verbose_name='State'),
        ),
    ]
