# Generated by Django 4.1.1 on 2023-06-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_drone_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='serialNumber',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
