# Generated by Django 4.1.1 on 2023-06-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_drone_serialnumber_alter_medication_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
